### PR TITLE
Merge User into Develop

### PR DESCRIPTION
**Pull request by colbyktang**

### CODE REVIEW

**Review by tonywied17 — COMMENTED** [review]
Great job =]

**Review by hannahisprogramming — APPROVED** [review]

**Review by tonywied17 — APPROVED** [review]
Lgtm

**Comment by NewPagodi** [comment]
FWIW, the security hotspots are because of using `http` instead of `https` in the tests.  I'm fine with ignoring the warning if necessary, but can the test be changed to avoid it?

**Comment by NewPagodi** [comment]
Making the change didn't seem to affect the currne state of testing results, so I went pushed it

**Review by NewPagodi — APPROVED** [review]
I haven't looked over all the details, but this all seems good.

**Comment by NewPagodi** [comment]
I'm not sure why sonarcloud isn;t reporting coverage information, but the current stats are:
```
Statements   : 44.23% ( 184/416 )
Branches     : 39.74% ( 31/78 )
Functions    : 27.36% ( 26/95 )
Lines        : 42.55% ( 163/383 )
```

**Pull request merged**
