### PR TITLE
FRONTEND Merge Develop into Main

### PR DESCRIPTION
**Pull request by colbyktang**
This is the big one

### CODE REVIEW

**Comment by colbyktang** [comment]
This is where we should address bugs and code smells

**Review by dcee96 — DISMISSED** [review]
LGTM please review the bug if you haven't though. I'm at my other job rn so I don't have a laptop in front of me.

**Comment by NewPagodi** [comment]
I did not do that.  Github must have done that automatically.

**Comment by NewPagodi** [comment]
On the duplicate selectors for

```
.mat-button.mat-primary,
.mat-icon-button.mat-primary,
.mat-stroked-button.mat-primary {
    background-color: var(--rev-secondary);
    color: #fff;
    margin-right: 1.4em;
}

.mat-button.mat-primary,
.mat-icon-button.mat-primary,
.mat-stroked-button.mat-primary {
    margin-right: 1.2em;
}
```

I guessed that we were supposed to remove the second one.  The difference will only be .2em anyway.  I can only hope that doesn't break the layout somewhere.

**Comment by NewPagodi** [comment]
The remaining issue is that it doesn't like the number of parameters for `UserMiniDTO`.

**Comment by NewPagodi** [comment]
It took me 3 tries, but sonar cloud is wrong on this one issue, It's complaint is that

> A long parameter list can indicate that a new structure should be created to wrap the numerous parameters or that the function is doing too many things.

But User is the structure we're trying to create and it needs all of those things.  Since the long parameter list is really needed, I just had sonar cloud ignore the line the constructor is on.

**Comment by NewPagodi** [comment]
All CI checks are passing.  Hopefully I didn't break anything making the necessary changes.

**Review by NewPagodi — APPROVED** [review]
Everything but the changes made for CI was reviewed previously.

**Review by hannahisprogramming — APPROVED** [review]

**Pull request merged**
