### PR TITLE
Search sean

### PR DESCRIPTION
**Pull request by SCJackson929**
I fixed the problem where the log-in button shows up when switching pages and the username and profile image on the navbar go away. Also, I made more stuff into buttons.

### CODE REVIEW

**Review by devinabreu10 — APPROVED** [review]

**Review by NewPagodi — COMMENTED** [review]
LGTM

**Review by NewPagodi — APPROVED** [review]

**Comment by colbyktang** [comment]
Chrome 104.0.5112.102 (Windows 10): Executed 104 of 104 (48 FAILED) (0.615 secs / 0.517 secs)
TOTAL: 48 FAILED, 56 SUCCESS

**Comment by colbyktang** [comment]
Test cases are failing

**Comment by colbyktang** [comment]
Ok nevermind it fails on develop too

**Pull request merged**
